### ISSUE TITLE
Public.java uncommented

### ISSUE THREAD

**Issue by Avery-Whitaker** [FRC1076/FRC1076-2015-Competition_Robot#2]
I do not understand the function of Public.java. It needs to be better documented to ensure proper use. It also appears to not follow proper OOP paradigm, with public variables that should be private.

Please fix this very critical issue.

**Comment by vivianbp** [comment]
I agree, this lack of comments is unacceptable. But I request Avery add them as punishment/retribution for the Robofest code, since I had to do it for him then :P

**Comment by Avery-Whitaker** [comment]
I agree with Victor's sentiment that the lack of comments is unacceptable. Because he discovered the issue, I propose he is in the best position to fix it. Therefore I have assigned this issue to him.

**Comment by vivianbp** [comment]
Avery that's a lie. Look at the initial report you submitted. It clearly states that there is not enough documentation.

**Comment by Avery-Whitaker** [comment]
I in no way specified that the documentation must be in source code commenting. Therefore you were the first person to mentioned inline documentation.

**Comment by Avery-Whitaker** [comment]
![markdown powers!](http://memecrunch.com/image/511b0412afa96f233500001a.jpg?w=259)

**Comment by EvilJuiceBox** [comment]
So question is, are we acutally totally done with coding already?
